### ISSUE TITLE
global: upgrade to python3

### ISSUE THREAD

**Issue by roksys** [reanahub/reana-workflow-engine-yadage#114]
Currently RWEY uses python2.7 (end of support in 2020), we should upgrade to python3.7

**Comment by tiborsimko** [comment]
We can switch to Python 3 as part of global Yadage upgrade https://github.com/reanahub/reana-client/issues/251

**Comment by dprelipcean** [comment]
When running `make deploy` I get the following error:
```console
/home/dprelipc/.virtualenvs/reana/local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```
and according to [this issue](https://github.com/streamlink/streamlink/issues/2448), upgrading to `python3` solves it.

**Comment by tiborsimko** [comment]
@dprelipcean You can safely switch to using Python 3.7 as the main Pyhton version on your host systems so that `reana-cluster`, `reana-dev` and friends would use Python 3 already.

We are using Python 2.7 only in a few remaining places, notably *inside* the cluster in `reana-workflow-engine-cwl` and `reana-workflow-engine-yadage` components... We should migrate these as well to Python 3 once the Yadage and CWL version upgrade is done.

**Comment by dprelipcean** [comment]
Solved as as part of [this pr](https://github.com/reanahub/reana-workflow-engine-yadage/pull/122).
