### ISSUE TITLE
setup: install `reana-commons[yadage]` & remove `yadage` deps.

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-workflow-engine-yadage#192]
https://github.com/reanahub/reana-commons/blob/fae41c1d3c13580cc5c0ec5a030161a7f35b41ea/setup.py#L30

https://github.com/reanahub/reana-workflow-engine-yadage/blob/24cb3f95632a04c58c328c28f42dd3a87b4aa5f3/setup.py#L57-L58

Update `requirements.txt` accordingly using `pip-compile`.

**Comment by tiborsimko** [comment]
Beware of other dependencies that we needed to pin inside `r-w-e-yadage`. Notably `adage`.  It may be good to keep the full the trio (adage, yadage, yadage-schema) pinned to the same values.  Which would call for pinning _also_ adage in reana-commons.

The second comment is that there are other dependencies that are pinned in `r-w-e-yadage` :

```
    "adage==0.10.1",  # FIXME remove once yadage-schemas solves yadage deps.
    "pyOpenSSL==19.0.0",  # FIXME remove once yadage-schemas solves deps.
    "rfc3987==1.3.8",  # FIXME remove once yadage-schemas solves yadage deps.
    "strict-rfc3339==0.7",  # FIXME remove once yadage-schemas solves deps.
    "webcolors==1.9.1",  # FIXME remove once yadage-schemas solves yadage deps.
```

but I guess we won't have to pin these inside `r-commons` since these will be most probably not needed for DAG complexity calculations...
